# se definen las etapas que se ejecutarán en orden secuencial
stages:
  - test
  - quality
  - build
  - deploy

image: python:3.13-slim

# se le dice a pip dónde guardar los archivos descargados
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# se guarda esa carpeta entre distintos pipelines
cache:
  paths:
    - .cache/pip
  when: always

# ETAPA 1: tests unitarios
run_tests:
  stage: test
  script:
    - echo "Instalando SOLO dependencias ligeras para la lógica..."
    - pip install pytest numpy opencv-python-headless pillow
    - echo "Ejecutando tests de utilidades matemáticas..."
    - pytest tests/test_utils.py

# ETAPA 2: métricas de calidad
check_quality:
  stage: quality
  script:
    - echo "Instalando herramienta de métricas..."
    - pip install radon
    - echo "Analizando la complejidad ciclomática del código..."
    # se analiza la carpeta backend
    # '-s' muestra la nota (A, B, C...) y '-a' muestra la media total.
    - radon cc backend/ -s -a

# ETAPA 3: empaquetado
build_package:
  stage: build
  script:
    - echo "Empaquetando el código limpio del proyecto..."
    # se comprimen las carpetas esenciales en un archivo llamado 'proyecto_sawubona.tar.gz'
    # se excluyen entornos virtuales locales
    - tar -czf proyecto_sawubona.tar.gz backend/ frontend/ requirements.txt pytest.ini
  artifacts:
    name: "paquete-instalacion-$CI_COMMIT_SHORT_SHA" # nombre dinámico con el ID del commit
    paths:
      - proyecto_sawubona.tar.gz # archivo que GitLab guardará en su web
    expire_in: 1 week # se borra automáticamente en una semana para ahorrar espacio

# ETAPA 4: despliegue al CESGA
deploy_to_cesga:
  stage: deploy
  script:
    - echo "Iniciando despliegue automático en el CESGA..."
    - echo "Aquí irán los comandos SSH para reiniciar el servidor FastAPI"