# se definen las etapas que se ejecutarán en orden secuencial
stages:
  - test
  - quality
  - build
  - deploy

image: python:3.13-slim

# ETAPA 1: tests unitarios
run_tests:
  stage: test
  script:
    - echo "Instalando SOLO dependencias ligeras para la lógica..."
    - pip install pytest numpy opencv-python-headless pillow
    - echo "Ejecutando tests de utilidades matemáticas..."
    - pytest tests/test_utils.py

# ETAPA 2: métricas de calidad
check_quality:
  stage: quality
  script:
    - echo "Instalando herramienta de métricas..."
    - pip install radon
    - echo "Analizando la complejidad ciclomática del código..."
    # se analiza la carpeta backend
    # '-s' muestra la nota (A, B, C...) y '-a' muestra la media total.
    - radon cc backend/ -s -a

# ETAPA 3: empaquetado (Versión ligera para evitar límite 413)
build_package:
  stage: build
  script:
    - echo "Empaquetando el código fuente limpio del proyecto..."
    - tar -czf proyecto_sawubona.tar.gz backend/ frontend/ requirements.txt pytest.ini
  artifacts:
    name: "paquete-fuente-$CI_COMMIT_SHORT_SHA"
    paths:
      - proyecto_sawubona.tar.gz
    expire_in: 1 week

# ETAPA 4: despliegue automático en el CESGA
deploy_server:
  stage: deploy
  tags:
    - cesga-runner
  script:
    - echo "Desplegando localmente desde el interior del CESGA..."
    - module load cesga/system miniconda3
    
    - export PATH=/usr/bin:/bin:$PATH  
    
    - source activate sawubona_env
    - export PYTHONPATH=\$STORE/librerias_gpu:\$PYTHONPATH
    - cd ~/usc-sawubonareloaded
    - echo "Forzando sincronización exacta con GitLab..."
    - git fetch origin main
    - git reset --hard origin/main
    - git clean -fd
    - echo "Reiniciando Uvicorn..."
    - pkill -f uvicorn || true
    - nohup uvicorn backend.main:app --host 0.0.0.0 --port 8000 > uvicorn.log 2>&1 &
    
    - echo "Registrando la fecha del despliegue en el README..."
    - echo "- Despliegue automático exitoso en el CESGA el $(date +'%d/%m/%Y a las %H:%M:%S')" >> README.md
    - git config user.email "bot-cesga@sawubona.local"
    - git config user.name "CESGA Deploy Bot"
    - git add README.md
    - git commit -m "docs - registrar fecha de último despliegue [skip ci]" || echo "No hay cambios para commitear"
    - git push origin main